const types = {
  USER_INPUT_SEARCH: "USER_INPUT_SEARCH",
  USER_SELECTED_VIDEO: "USER_SELECTED_VIDEO",
  FETCH_WIKIPEDIA_TERM: "FETCH_WIKIPEDIA_TERM",
  SELECT_LIGHT_THEME: "SELECT_LIGHT_THEME",
  SELECT_DARK_THEME: "SELECT_DARK_THEME",
  SELECT_BLUE_THEME: "SELECT_BLUE_THEME",
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  SAVE_USER_SEARCH_TERM: "SAVE_USER_SEARCH_TERM"
};
export default types;
